### ISSUE TITLE
How to handle brackets in comments?

### ISSUE THREAD

**Issue by CoenraadS** [CoenraadS/BracketPair#1]
Option 1:  
* Leave as is. Its not a big problem and adding comment checks could have a hit on performance

Option 2:  

* Don't colorize in comments

Option 3: 
* Colorize in comments, but limit bracket counting scope to comment block

I like 3 best assuming performance hit isn't too bad.

**Comment by Arithmeticae** [comment]
I'm partial to option 2, it maintains consistency with how comments are usually treated in code (no syntax highlighting etc).

**Comment by sumigoma** [comment]
Within comments you're less likely to have complex logic that requires multiple brackets. 

For code that is commented out, you've probably already verified the brackets match, or you can always do the check after uncommenting when the code is live again.

**Comment by jankap** [comment]
I'd like to see an option to disable the feature in comments, sometimes it's confusing especially if the comments don't have a high contrast an then there is some yellow or red color in it.

Thank you anyway for this cool extension!

**Comment by CoenraadS** [comment]
Thanks for the feedback, I will try to add option 2 soon.

**Comment by CoenraadS** [comment]
Comments will now be ignored in v0.5.0. If you would like the old behavior back it can be toggled using the `"bracketPairColorizer.colorizeComments"` setting.
