### ISSUE TITLE
What do i have to tweak?

### ISSUE THREAD

**Issue by f0rsakenc0der** [CoenraadS/BracketPair#101]
I am using VSCode and i have configured some settings for the extension, and it works for my CSS file. 
But not in my HTML file. Do i have to set something more?

**Comment by CoenraadS** [comment]
```
	"bracketPairColorizer.consecutivePairColors": [
		"()",
		"[]",
		"{}",
		[
			"</",
			">"
		],
		[
			"<",
			"/>"
		],
		"<>",
		[
			"Gold",
			"Orchid",
			"LightSkyBlue"
		],
		"Red"
	],
```

**Comment by joshkellough** [comment]
This does not colorize the three types of non-angle brackets in HTML for me. That would be very useful for Django templating. I have also disabled all of my Python extensions and it makes no difference.

**Comment by joshkellough** [comment]
Are brackets colorized for you when you have a plain HTML file open, or just templating/Angular?

**Comment by CoenraadS** [comment]
@joshkellough I'd dependent on this list: http://prismjs.com/#languages-list

**Comment by joshkellough** [comment]
You said it doesn't work with templating languages and Angular but you didn't say anything about regular, plain HTML. That's what I'm asking. HTML files, whether a Django template or not, are the only type of file I use in which the brackets {}, (), and [] are not colorized. HTML is not on the Prism language list but Django is. But towards the top of the page you provided they talk about HTML highlighting. I'm trying to see if my issues stem from me missing something or if HTML just isn't working before I submit an issue.

**Comment by CoenraadS** [comment]
HTML Files will only color {} () [] inside <script> tags. However this is also broken atm: https://github.com/CoenraadS/BracketPair/issues/108

**Comment by joshkellough** [comment]
That's unfortunate. It would be helpful in Django. Also, I just tried using  brackets between script tags and they were colorized. On an unrelated note, I'm really digging the  new scope feature. Thanks for that.

**Comment by CoenraadS** [comment]
I know, I really want to support template files to. Its on my todo list 👍

**Comment by joshkellough** [comment]
You're doing great so far. Keep it up.
