### ISSUE TITLE
BracketPair Settings: Cannot find module './prism-makefile'

### ISSUE THREAD

**Issue by Bourgeois-Maxime** [CoenraadS/BracketPair#103]
Hi, just got this error when using you're awesome extension on VS Code Windows 10. Works great on my linux. Can you help ?

**Comment by CoenraadS** [comment]
Interesting, never seen this error before and didn't release a new version recently. Did you recently install any other coloring extensions? I had some conflicts with them before.

**Comment by leihuagh** [comment]
I got same problem.  Windows 10 with new visual studio code version 1.22.1

**Comment by CoenraadS** [comment]
Could you please list any other extensions you have installed?
