### ISSUE TITLE
highlightActiveScope not working correctly?

### ISSUE THREAD

**Issue by tehtrav** [CoenraadS/BracketPair#105]
With settings like so:

`"bracketPairColorizer.highlightActiveScope": true,`
`"bracketPairColorizer.activeScopeCSS": "backgroundColor : {color}"`

There doesn't seem to be highlighting of scope

![screen shot 2018-04-03 at 2 20 48 pm](https://user-images.githubusercontent.com/351975/38267747-5d17f7aa-374a-11e8-8add-00035984bed1.png)

**Comment by CoenraadS** [comment]
Does it work on the .json file? Untitled files have no language-id and arn't colored

**Comment by CoenraadS** [comment]
Try like:

```
	"bracketPairColorizer.activeScopeCSS": [
		"backgroundColor : {color};"
	]
```
