### ISSUE TITLE
[Feature Request] Show bracket pair in the gutter

### ISSUE THREAD

**Issue by duranivan** [CoenraadS/BracketPair#106]
It would be great if the bracket pair could be shown in the gutter as well (as an option of course), just like bracket hightlighter in Sublime.

You guys added the `"bracketPairColorizer.activeScopeCSS"` which is great. Thanks 👍🏼.

**Comment by CoenraadS** [comment]
Could you post a screenshot of how it looks like in sublime? How do you expect the gutter to look?

**Comment by duranivan** [comment]
Sure, here are a couple:

![screen shot 2018-04-12 at 10 06 30 pm](https://user-images.githubusercontent.com/20104703/38692840-7dda0c8e-3e9e-11e8-98dc-ebd23762477a.png)
![screen shot 2018-04-12 at 10 12 56 pm](https://user-images.githubusercontent.com/20104703/38692912-bc57b70e-3e9e-11e8-855f-b75e87eb6b06.png)
![screen shot 2018-04-12 at 10 10 38 pm](https://user-images.githubusercontent.com/20104703/38692859-8dcb8712-3e9e-11e8-865f-819cb73be267.png)

**Comment by CoenraadS** [comment]
This was fun to implement, thanks for the request.

It should be in v1.0.29 behind the `showBracketsInGutter` setting. Happy to hear some feedback.

**Comment by CoenraadS** [comment]
What kind of behaviour is expected if there is text between the lines?

![image](https://user-images.githubusercontent.com/5593825/38767465-ec41bf34-3fe1-11e8-9267-415bce722d3d.png)

Or is the line always in column 0?

**Comment by duranivan** [comment]
Regading [vscode issue #5923](https://github.com/Microsoft/vscode/issues/5923), that's really annoying, I agree. I had noticed this before in another extension (Quokka). I was really looking forward to try this feature in the new release, but I also use breakpoints a lot so that's definitely a problem.

Regarding the line, those are indentation guides, and in vscode I use the extension ['Guides'](https://marketplace.visualstudio.com/items?itemName=spywhere.guides) and it works just fine. So actually I was not requesting that feature, it just happened to show in the screenshots above as I have them enabled as well in Sublime.

Thanks a lot for your efforts. Hope there is a way around issue #5923.

**Comment by duranivan** [comment]
Just checked it out. Looks great, and actually it is not that difficult to set breakpoints (either with F9 or just go out of the bracket), so I'm not finding it to be a problem really.

Thanks a lot 👍🏼

**Comment by CoenraadS** [comment]
I added guides anyway because I have all the information for it anyway.

![image](https://user-images.githubusercontent.com/5593825/38777529-d0ceacda-40a9-11e8-90b9-6a05e3ccef7c.png)

You can check it out with: `"bracketPairColorizer.showVerticalScopeLine": true`

**Comment by duranivan** [comment]
Great additions. Thanks again!
