### ISSUE TITLE
Module attributes in Elixir lead to an error

### ISSUE THREAD

**Issue by optikfluffel** [CoenraadS/BracketPair#109]
When using [module attributes in Elixir](https://elixir-lang.org/getting-started/module-attributes.html) the closing bracket isn't matched anymore.

![screen shot 2018-04-15 at 12 39 03](https://user-images.githubusercontent.com/379915/38777546-21221e4c-40aa-11e8-8d16-71eb919104bb.png)

Example Code:

```elixir
defmodule BrakeBracketPairColorizer do
  @fixed "foo"

  def foobar() do
    foo = String.upcase(@fixed)

    foo <> "BAR"
  end
end

```

**Comment by CoenraadS** [comment]
Tracking here: https://github.com/PrismJS/prism/issues/1392
