### ISSUE TITLE
[Feature Request] Select text within scope

### ISSUE THREAD

**Issue by duranivan** [CoenraadS/BracketPair#110]
Since you just added scope lines and brackets in gutter (as in #106), would it be possible to add a keyboard shortcut (or command) to select/highlight the current scope? The vscode default `Expand selection` does not quite do the job.

Thanks in advance!

**Comment by CoenraadS** [comment]
I added it 👍 

Here is a quick-start:

```
	{
		"key": "shift+alt+right",
		"command": "bracket-pair-colorizer.expandBracketSelection",
		"when": "editorTextFocus"
	},
	{
		"key": "shift+alt+left",
		"command": "bracket-pair-colorizer.undoBracketSelection",
		"when": "editorTextFocus"
	}
```

**Comment by duranivan** [comment]
Awesome! It's working great. Thanks a lot :)
