### ISSUE TITLE
BracketPair no longer works

### ISSUE THREAD

**Issue by myrddincat** [CoenraadS/BracketPair#112]
BracketPair has stopped working altogether. I code in Apex, and the brackets in my code are all white. (When I swap to another language, the brackets become colored again)

![bracketpair](https://user-images.githubusercontent.com/1756142/38807150-a80e2bf4-4149-11e8-8bc6-36122f535b7f.png)

**Comment by CoenraadS** [comment]
Thanks for reporting. I will include this in the next release

**Comment by CoenraadS** [comment]
Should be fixed in v1.0.37

PrismJs doesn't support this language so I mapped to be treated as Java
