### ISSUE TITLE
Alignment of outline incorrect when mixed tabs and spaces

### ISSUE THREAD

**Issue by dakaraphi** [CoenraadS/BracketPair#114]
Example of JS

![image](https://user-images.githubusercontent.com/10656375/38815806-bafeb0bc-4162-11e8-8e5a-38592841ea8f.png)

**Comment by CoenraadS** [comment]
Do you use

`
"editor.insertSpaces": false,
`

or is this caused by the formatter? I'm wondering if I can just read the vscode settings to save the performance overhead of parsing each line myself

**Comment by dakaraphi** [comment]
@CoenraadS I do not use that setting.
Unfortunately, I work on a very large codebase where mixed tabs and spaces are already prevalent.
If you think it is going to be too much of a performance hit, then it might be something you can't support. 

FYI, I had to deal with this for my Fold Plus extension.  For reference, these are the functions I used for that. `calculateColumnFromCharIndex` and `calculateCharIndexFromColumn`.  I also didn't find any other way to get the values other than parsing the lines.
https://github.com/dakaraphi/vscode-extension-common/blob/7a86f594b9e30ad14413b2d5e03680b23ff3d6d6/src/EditorFunctions.ts#L360

**Comment by CoenraadS** [comment]
Thanks for the link, I'll look into it. Usually scopes arn't very large so maybe its not a problem

**Comment by CoenraadS** [comment]
If you want to try a PR to make sure it works for your situation it's probably around: https://github.com/CoenraadS/BracketPair/blob/cc6598b49179f3d62170f8427e5c9e97206853e4/src/documentDecoration.ts#L286

My code is kinda messy though

**Comment by dakaraphi** [comment]
Thanks, I will take a look as soon as I have a chance.

**Comment by dakaraphi** [comment]
So I gave it a try anyway, and looks like in practice it actually lines up 99% of the time.  At least in the sample documents tried so far.  Maybe needing to draw through a tab is more of an edge case than I thought.  I might experiment just a bit more to see if this will be viable.

**Comment by CoenraadS** [comment]
@dakaraphi 

You might be interested in this hack to render on empty lines for your extension: 

https://github.com/CoenraadS/BracketPair/blob/d60719cc8bf0e115a2d463b7b58b14bfc849220a/src/settings.ts#L264-L266

You can render decorations on a valid line then offset them to the empty line.

**Comment by dakaraphi** [comment]
@CoenraadS Awesome Thanks! that looks useful.
