### ISSUE TITLE
Inline comments breaks matching

### ISSUE THREAD

**Issue by dakaraphi** [CoenraadS/BracketPair#12]
![image](https://cloud.githubusercontent.com/assets/10656375/22987594/50739c50-f37d-11e6-8604-8ee4f4c6745f.png)

**Comment by CoenraadS** [comment]
Thanks for the report, you can disable it for now with the `"bracketPairColorizer.colorizeComments"` setting.

On a side note, ofc my test-case for this was `/*()*/()/*()*/` which happens to work correctly

**Comment by CoenraadS** [comment]
Should be fixed in v0.7.2

**Comment by CoenraadS** [comment]
You may want to make sure you updated to v0.7.4, just squashed a couple more bugs related to commenting that you may encounter.
