### ISSUE TITLE
bracketPairColorizer.scopeLineCSS vertical line is not aligning with indentation level

### ISSUE THREAD

**Issue by christianalares** [CoenraadS/BracketPair#121]
As the screenshot below shows there is a hole in the vertical line if you have not indented the empty lines to the same lever as the other scope.
![bracketPairColorizer.scopeLineCSS vertical line](https://image.ibb.co/kFuhRx/Screen_Shot_2018_04_23_at_16_22_47.png)

Expected behaviour:
The coloured indent lines (in my case the white one) should be drawn solid to the end of it's scope even if some lines in between are not indented to the same lever or more.

Is this something that can be fixed?

**Comment by CoenraadS** [comment]
Thanks for the report, this is a limitation of vscode that I can't fix
