### ISSUE TITLE
bracketPairColorizer.consecutivePairColors configuration not working?

### ISSUE THREAD

**Issue by dannymcgee** [CoenraadS/BracketPair#123]
EDIT: I've discovered the problem — consecutivePairColors only works with colorMode: Consecutive. Using independentPairColors instead works. Making this a little bit more obvious in the documentation may mitigate some confusion.

I'm trying to use this code to customize the colors to make them a little less gaudy and to fit my theme better:

    "bracketPairColorizer.consecutivePairColors": [
        "()",
        "[]",
        "{}",
        [
            "#DBE6EC",
            "#AEC1CC",
            "#87a3b3"
        ],
        "#FA5E5B"
    ]

But it doesn't seem to be having any effect. I'm still getting the default Gold, Orchid, LightSkyBlue colors. I've saved and reloaded the window, and added the above block to the very top of my user settings file, but no dice. Am I doing something wrong? The other configuration lines in the screenshot are working just fine.

![custom-bracket-colors-not-working](https://user-images.githubusercontent.com/13191586/39217994-59cc91a8-47f0-11e8-9265-5429cd73b615.png)

**Comment by IllusionMH** [comment]
@dannymcgee you are using `"bracketPairColorizer.colorMode": "Independent"` therefore you should use `bracketPairColorizer.independentPairColors`.

Setting `"bracketPairColorizer.consecutivePairColors"` is only used when you set `"bracketPairColorizer.colorMode": "Consecutive"`.

**Comment by CoenraadS** [comment]
Thanks for the feedback, I will review if two separate configurations are actually needed
