### ISSUE TITLE
What is the entry point?

### ISSUE THREAD

**Issue by inunotaisho26** [CoenraadS/BracketPair#124]
What is the entry point to the Bracket Pair extension? 

I am writing a C-sharp path autocomplete extension for Visual Studio Community Mac [here](https://github.com/inunotaisho26/path-autocomplete).

I am writing another C-sharp extension for Visual Studio Community Mac that will mirror BracketPair. I need the entry point so I can build my file structure.

**Comment by CoenraadS** [comment]
All events are in https://github.com/CoenraadS/BracketPair/blob/master/src/extension.ts

**Comment by inunotaisho26** [comment]
your joining a pretty big club!!
