### ISSUE TITLE
Empty line not rendering vertical bracket line

### ISSUE THREAD

**Issue by wraytw** [CoenraadS/BracketPair#127]
Working with javascript in VSCode and I would love if the vertical match lines would render when the line is empty. Is there a way this could be enabled with a setting?

See in the image below how the empty code lines don't get a vertical bracket matched line?

<img width="365" alt="screen shot 2018-04-29 at 11 55 16 pm" src="https://user-images.githubusercontent.com/15827892/39416303-24537740-4c09-11e8-8d42-bf33425c28b6.png">

Thanks.

**Comment by CoenraadS** [comment]
This is fixed in v1.0.40. This version is linked to the new vscode version however, so either use insiders or wait for the next vscode to come out shortly to receive the update.

**Comment by heroboy** [comment]
@CoenraadS 
It is not correct
![default](https://user-images.githubusercontent.com/54468/39695545-8d11896a-521d-11e8-9833-0b8dc16f9378.png)

**Comment by CoenraadS** [comment]
@heroboy 

huh that's weird

```
function each(fn)
{
    for (var i = 0; i < this.length; ++i)
    {

        var obj = this[i];
        top_q.push(obj);
        var ret = fn(obj);
        top_q.pop();
    }
}

![image](https://user-images.githubusercontent.com/5593825/39695968-90091b78-51ec-11e8-9b3e-a409a11095da.png)

Could you perhaps show a screen shot with whitespace rendering on?
````

**Comment by heroboy** [comment]
@CoenraadS use tab indent, especially the indent before the open brace.

**Comment by CoenraadS** [comment]
@heroboy Found the issue, will be fixed in next release
