### ISSUE TITLE
Background Color Between Paired Brackets Of The Same Level

### ISSUE THREAD

**Issue by Cicin411** [CoenraadS/BracketPair#13]
What  I really admired is:

DIY the background color between the paired brackets, which are of the same level depending on the cursor positon.

e.g.

```javascript
1	for (var abc1 = 0; abc1 < arrar1.length; abc1++) {①L
2	    var element1 = array1[abc1];
3	    for (var abc2 = 0; abc2 < array2.length; abc2++) {②L
4	        var element2 = array2[abc2];
5	        if (!0) {③L
6	            var element3 = "hello world"
7	        }③R
8	    }②R
9	}①R
```
when the cursor is in the line2 or line3 ,  then all the contents between ①L and ①R have a background color.
when the cursor is in the line4 or line5 ,  then all the contents between ②L and ②R have a background color.
when the cursor is in the line6 ,  then all the contents between ③L and ③R have a background color.
...

Thanks for your useful extension.

**Comment by pr-yemibedu** [comment]
Hello,
 Maybe a little more context or a clearer example would help. 

-  How would the list of background choices be picked? (extend the existing list with a final bg color)
-  What would be the color scheme notion used? (comment color, #FFF, red)
-  Should every level have a unique color or should every color have a unique anti-color? (#F0F -> #0F0)
-  Should there just be a single "shade" up or down from the existing background? (#FFF -> #EEE)
- Should there be a list of exclusion characters? (whitespace, CRLF, tab)
- When is the context understood to be a yay or nay? (color brace, no-color paren, color bracket)

It is seems understandable what you want to occur but not how or if there are any constraints to consider. Thank you. Good day.

**Comment by CoenraadS** [comment]
I've been experimenting with this idea:

![highlight](https://cloud.githubusercontent.com/assets/5593825/23530855/def37a9a-ffa3-11e6-982a-df150368b852.gif)

I like it, however I need to figure out what is the best way to show the scope without it getting in the way or decreasing visability.

**Comment by pr-yemibedu** [comment]
Hello,
 So two things to add on this:
    * one is to do a post process on the string to trim the leading and trailing whitespace from being highlighted. 
    *  it may make sense to have a dedicated color group for this. the colors are louder than I would first guess. I would have for example picked grey blue and green sets.
    * it looks like there is a default highlight, unless actually inside of a pair, that should likely not happen.
This is awesome. Keep up the amazing hacking. Thank you. Good day.

**Comment by CoenraadS** [comment]
I added a scope line which I think looks nice
