### ISSUE TITLE
Support for VS Code's Gradle language setting

### ISSUE THREAD

**Issue by DavidPotter** [CoenraadS/BracketPair#131]
Please include the language you are using, a screenshot, and copy/pastable example.

I'm using a bunch of languages, including TypeScript, C#, Java, Bash, Kotlin, Gradle/Groovy, etc.  I notice that sometimes TypeScript identifies the language for a `build.gradle` file as Gradle instead of Groovy, and as a result Bracket Pair Colorizer doesn't colorize the brackets.  Is there a way to associate the two languages in Bracket Pair Colorizer?

**Comment by CoenraadS** [comment]
Sure thing! I mapped it to groovy in v1.0.49
