### ISSUE TITLE
Add support or separate backgroundColor and borderColor

### ISSUE THREAD

**Issue by PixelT** [CoenraadS/BracketPair#134]
It's possible to support backgroundColor which have separate opacity value than borderColor have?
I would like to have horizontal + vertical scope lines with opacity 1 + add background color to property which has opacity 0.2. My settings code is:
```
    "bracketPairColorizer.scopeLineCSS": [  
        "backgroundColor : {color}; opacity: 0.15",
        "borderStyle : solid",
        "borderWidth : 1px",
        "borderColor : {color}; opacity: 1"
    ],
```
but I have borderColor + backgroundColor always in this same opacity. It's possible to separate it?

**Comment by CoenraadS** [comment]
It is possible, I but requires code changes. I will look into it because this is a really cool effect with `borderColor` and scopeLine that I didn't even know about

**Comment by CoenraadS** [comment]
I'll leave this open for now until I'm sure its working correctly

**Comment by CoenraadS** [comment]
wow that was a poor release, should be working now for real in 1.0.53

**Comment by PixelT** [comment]
It works perfect, thanks!

**Comment by CoenraadS** [comment]
I had to roll-back the release as a dependency broke some global objects, hope to bring it back soon

**Comment by PixelT** [comment]
OK. Please write comment here (or open this issue right now), when it will be available again. Thanks :)

**Comment by CoenraadS** [comment]
and its back again

**Comment by Rasarts** [comment]
Is backgroundColor opacity of activeScopeCSS should work?

**Comment by CoenraadS** [comment]
@Rasarts No, I have to add that separately
