### ISSUE TITLE
Flow doesn't start with bracketPairColorizer plugin

### ISSUE THREAD

**Issue by romanlex** [CoenraadS/BracketPair#136]
#Hello...My Flow server doesn't start with this plugin
When I disable it - all work properly
Arch Linux, Last version of vscode, Bracket Pair plugin and flow
I use workspace settings:
```
{
  "javascript.validate.enable": false,
  "gitflow.default.development": "master",
  "flow.useNPMPackagedFlow": true,
  "flow.useLSP": true,
  "flow.pathToFlow": "${workspaceRoot}/client/node_modules/.bin/flow"
}
```

**Comment by betaorbust** [comment]
I just ran into this as well.
Deep in the flow extension, it was using rxjs which was trying to load either window or global. Having this extension installed turned global into:
```json
 {"$c":{},"Colors":{}}
```
which was not great for everything after that.
I posted my rundown here: https://github.com/flowtype/flow-for-vscode/issues/247#issuecomment-391172088

**Comment by browne0** [comment]
since this just started happening for me today, and I have auto updates on I'm assuming it's related to this PR? 👀 

https://github.com/CoenraadS/BracketPair/commit/7f71bc24121d3327be7d4ee7b9f9476ecf3a5209

**Comment by betaorbust** [comment]
No smoking gun, but that commit includes colors.js, which modifies the global String prototype.
That seems dangerous on a good day...

**Comment by CoenraadS** [comment]
Thanks for the investigation 👍 , I will try to remove the colors.js dependency later today

**Comment by browne0** [comment]
Thank you for putting out a timely fix
