### ISSUE TITLE
[Language Support] ObjectPascal

### ISSUE THREAD

**Issue by pakLebah** [CoenraadS/BracketPair#140]
This extension doesn't support `ObjectPascal` language. I'm using [OmniPascal](https://marketplace.visualstudio.com/items?itemName=Wosi.omnipascal) extension and [Free Pascal](http://freepascal.org) to write Pascal programs on VS Code. So, how to make this extension works with ObjectPascal language, especially on the `begin … end` pair?

Thank you. 😊

**Comment by CoenraadS** [comment]
I don't use Pascal, but I added keyword support for it in v1.0.56

Try something like

```
	"bracketPairColorizer.consecutivePairColors": [
		"()",
		"[]",
		"{}",
		["type","end"],
		["begin","end"],
		[
			"Gold",
			"Orchid",
			"LightSkyBlue"
		],
		"Red"
	],
```

**Comment by pakLebah** [comment]
It still doesn't work with Pascal files. 😟
