### ISSUE TITLE
Adding non-bracket scope lines

### ISSUE THREAD

**Issue by m4xc4v413r4** [CoenraadS/BracketPair#142]
Is there a way for me to add things like if/end, function/end and others to get the scope lines this extension does? Because they're so much better than what the editor gives us.

**Comment by CoenraadS** [comment]
![image](https://user-images.githubusercontent.com/5593825/40578345-c67dd52e-6112-11e8-88e3-f2623e000422.png)

I have to add it on a per-language basis. I can include lua support in the next release if you want. If there are other words that you want to be treated as brackets please tell me so I can test them also

**Comment by m4xc4v413r4** [comment]
Nice thanks man. If you tell me what I need to add I can do that, don't want to bother you with adding every little thing.

On Lua I would say the main scopes would be:

if | else | elseif | end
local function | end - the local isn't mandatory, and I don't know if multiple words work for you
for | end
while | end

Those are probably the most used scopes that don't have brackets.

**Comment by CoenraadS** [comment]
No worries, I enjoy supporting little things 👍 

It doesn't work yet until next release, but the config would look like this:

```
    "bracketPairColorizer.consecutivePairColors": [
        "()",
        "[]",
        "{}",
        [
            "function",
            "end"
        ],
        [
            "if",
            "end"
        ],  //etc
        [
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        "Red"
    ]
```

**Comment by m4xc4v413r4** [comment]
But you added something somewhere else to support this, right? Asking because before coming here I tried

```
    "bracketPairColorizer.consecutivePairColors": [
        "()",
        "[]",
        "{}",
        [
            "if",
            "end"
        ],
        [
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        "Red"
    ]
```
And it didn't seem to work, maybe i did something wrong, or indeed you had to "enable" this feature with some change somewhere else :)

**Comment by CoenraadS** [comment]
Yes, wait until next release :) Had to add keyword support for lua in the code

**Comment by m4xc4v413r4** [comment]
ok, thanks again

**Comment by pakLebah** [comment]
Will the next release solve #140 as well?
