### ISSUE TITLE
when open .sql file there is issue

### ISSUE THREAD

**Issue by agborkowski** [CoenraadS/BracketPair#145]
Im just opening sql file and im getting error in notification center like this: 
```
BracketPair Settings: Cannot find module './prism-sql'
```

editor slow down and there is the problem with editing files.

**Comment by CoenraadS** [comment]
That is unexpected. I just tried myself but cannot reproduce. Which version of the extension are you using?

**Comment by agborkowski** [comment]
outdated its not appear in new version of vscode
