### ISSUE TITLE
Extension does not work in my case

### ISSUE THREAD

**Issue by carlzacher** [CoenraadS/BracketPair#149]
I am working with PHP, HTML, and Javascript files at the moment. My VS Code version is at 1.20.1. Although it works in colorizing the bracket pairs, it fails to show the vertical and horizontal scope lines. Do I need to install other extensions or edit native settings for this feature to work? Right now I am using another extension named "Indenticator" to show scope lines but I have seen on other web pages how the Bracket Pair Colorizer scope lines look and it looks better. I've tried uninstalling all other extensions but it still did not work. Any thoughts on how to solve my case? Or do I just need to update my VS Code for this to work?

**Comment by CoenraadS** [comment]
It needs vscode 1.23

**Comment by carlzacher** [comment]
Oh I see. Well, thanks for the fast reply. Keep up the good work. :)
