### ISSUE TITLE
Support for other types of "brackets" (ABAP)

### ISSUE THREAD

**Issue by davidreza** [CoenraadS/BracketPair#151]
In programming languages like ABAP we use "brackets" like: IF (opening structure) with ENDIF (closing structure); DO-ENDDO, LOOP-ENDLOOP, FORM-ENDFORM and so on in order to determine the statements that belong to each type of statement.

It would be awesome if the extension could be more flexible when customizing the kind of "brackets" allowed in order to have these words as coloured brackets.

![image](https://user-images.githubusercontent.com/14788384/40868208-6113c12c-65d0-11e8-8dec-aa7f1664fead.png)

**Comment by CoenraadS** [comment]
In v1.0.57 try something like:

```
	"bracketPairColorizer.consecutivePairColors": [
		[
			"IF",
			"ENDIF"
		],
		[
			"Gold",
			"Orchid",
			"LightSkyBlue"
		],
		"Red"
	],
```
