### ISSUE TITLE
Support for Windows Batch (.bat) files

### ISSUE THREAD

**Issue by Kaedin** [CoenraadS/BracketPair#152]
Hi Developer,

For some reason, I'm not able to get my bracket pairs colorized in Windows Batch (.bat) files. I'm using the default settings and to make sure that the extension works in general, I've confirmed that brackets are getting colorized in e.g. PowerShell scripts. Should Batch files be supported by this extension?

Best regards,
IL

**Comment by CoenraadS** [comment]
Fixed in v1.0.58
