### ISSUE TITLE
Allow direct hex colors?

### ISSUE THREAD

**Issue by linhtto** [CoenraadS/BracketPair#176]
I see that the colors have to be from a list, and they'll then be translated into hex colors. Is it possible to allow hex colors directly, so that people can match the colors to their own themes, and also to basically make the number of colors unlimited?

Thanks for the extension!

**Comment by CoenraadS** [comment]
I think this already works ^°

**Comment by linhtto** [comment]
That's interesting because I tried and it's just white if I use something not in the list. See the code here https://github.com/CoenraadS/BracketPair/blob/master/src/colors.ts.

**Comment by linhtto** [comment]
I'm not sure how but I restarted my computer and it works now. Thanks and
sorry for making you check. Maybe the extension description can mention
this feature!
