### ISSUE TITLE
How to colorize the brackets in other language?

### ISSUE THREAD

**Issue by GiacomoZheng** [CoenraadS/BracketPair#177]
This extension sleeps when I write program in `racket`. In fact, so do the scheme and lisp.
![image](https://user-images.githubusercontent.com/35882458/44701896-5d921700-aac3-11e8-8e5e-94759fd36c16.png)
the extension of `racket` I used is `karyfoundation.racket`.

In the same time I want to use this extension to colorize the language created by myself, and I failed again.

I want to know whether there is a way for me to use it with only doing a little bit change in the source files. Not only in `racket`, but all the languages I need.

Thanks

**Comment by cvkline** [comment]
It looks like this extension does its syntax highlighting using Prism.js, which understands the syntax of many languages but not all.  Lisp and Scheme are on the list so they should be highlighted fine (I use Lisp myself without problems).  But Racket doesn't appear to be on the list which is probably why it is not functioning for you.

**Comment by GiacomoZheng** [comment]
I'm sorry that it was really my fault to write down the `Lisp` and `Scheme` in my description. It is true that it works under the Lisp and Scheme.

Now, what I cannot understand is that why this extension works for `Lisp` and `Scheme`, but not the `Racket`, as the syntax of them are similar (In fact, I just changed the language selection of the file above, and it works).

@cvkline. Thanks for your response. In fact, I want to understand why the it happens, as I want to overcome it. Is the "list" you wrote exist in the source files, and whether I can get what I want by change it?

Thanks

**Comment by GiacomoZheng** [comment]
I've done it by building some new files and add a new item in the a file of this extension.

**Comment by bryangingechen** [comment]
@GiacomoZheng Do you mind giving a few more details on what you did to fix this? I'm also trying to get this extension to work with a language that's not supported by Prism.js.

**Comment by GiacomoZheng** [comment]
I want to know if it is legal to do some change on others' extension, but I promise that I won't use it for business uses.

Here is the tutorial, which use the example of my win 10 pc.

For mac, I think it is similar.

Go to `.vscode/extensions/coenraads.bracket-pair-colorizer-1.0.59\node_modules\prismjs\` under your `admin`.

### you need to change three files
1. `components.js` and add two files in `components`, assume the language name is `<name>`
2. create a new file named `prism-<name>.js`, and another one
3. `prism-<name>.min.js`

you can reference the another files, if you still have any question, you can leave a pessage here.

**Comment by bryangingechen** [comment]
>I want to know if it is legal to do some change on others' extension, but I promise that I won't use it for business uses.

Assuming you're asking about the legality of modifying the prismjs code, I am not a lawyer, but I believe there should be no problem. [Prismjs is licensed under the MIT license](https://github.com/PrismJS/prism/blob/master/LICENSE) whose terms are quite permissive.

Thanks for the tutorial! I'll try it out and let you know if I get stuck.

**Comment by CoenraadS** [comment]
Thanks for the feedback. I am continuing development of this extension under a new project, Bracket-Pair-Colorizer-2. I have identified this issue as one that _may_ be fixed in the new version.

https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2

It is currently in alpha, but you are welcome to try it out.

**Comment by CoenraadS** [comment]
For v2 you can look at https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/blob/develop/LANGUAGE_SUPPORT.md
