### ISSUE TITLE
👏Thank you!

### ISSUE THREAD

**Issue by bgschiller** [CoenraadS/BracketPair#183]
My apologies for posting this as an issue; I couldn't find an email for your account.

I just wanted to say thank you! I'm teaching a small class of beginner programmers. One of my students was having a lot of trouble matching up their curly-brackets in JS and getting frustrated. I recommended that they try out your extension. Here's what they had to say:

> I found great satisfaction out of utilizing the recommended vs extension and tweaking my code to get results I could troubleshoot.  Thank you for pushing me in that direction and letting me figure it out for myself :slightly_smiling_face:

Thank you for helping my students be more self-sufficient and develop confidence in their own abilities!

**Comment by CoenraadS** [comment]
Ty so much, I've been struggling to find motivation to work on this project sometimes and comments like this really make my day 💯

**Comment by CoenraadS** [comment]
Thanks for the feedback. I am continuing development of this extension under a new project, Bracket-Pair-Colorizer-2.

https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2

It is currently in alpha, but you are welcome to try it out.
