### ISSUE TITLE
Support for PowerShell

### ISSUE THREAD

**Issue by commanderpoop** [CoenraadS/BracketPair#19]
Support for PowerShell would be great. 
A line comment is simply anything that follows a #
A comment block is like such: 

```
<#
blablabla
blablabla
blablabla
#>
```

**Comment by CoenraadS** [comment]
Hello

This is supported in the new `0.10.3` release. Let me know if you encounter any issues.

**Comment by commanderpoop** [comment]
Can confirm it works! Thanks for this!
