### ISSUE TITLE
fails to activate

### ISSUE THREAD

**Issue by capaj** [CoenraadS/BracketPair#20]
![image](https://cloud.githubusercontent.com/assets/1305378/25070086/3d417134-2294-11e7-8631-6d7e764b0065.png)

tested wit 0.10.0

**Comment by CoenraadS** [comment]
Thanks for the report. Unfortunately I am on vacation but hope to fix this
when I return.

**Comment by CoenraadS** [comment]
Do you have any custom settings?

**Comment by CoenraadS** [comment]
Should be fixed in 0.10.2
