### ISSUE TITLE
No colorization and no errors

### ISSUE THREAD

**Issue by tiangolo** [CoenraadS/BracketPair#21]
# Description

I can't see any colorization of brackets.

I tried with a `.ts` and `.js` file.

There are no errors (in the error / warning section in the status bar at the bottom).

I tried the other similar extension (and less complete, as I understand) and it worked: https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets

But of course I would like to use this extension given the advantages stated in https://github.com/CoenraadS/BracketPair/issues/5#issuecomment-264934372

Here's a screenshot after installing and reloading Visual Studio Code:

![screenshot from 2017-04-18 12-03-58](https://cloud.githubusercontent.com/assets/1326112/25143274/7007fa56-242f-11e7-8560-cc69aa32e89b.png)

# Version

I'm on Ubuntu 16.04

Visual Studio Code version:

```
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

I just installed the extension, so it should be the latest version, in the Changelog tab the latest release documented is `0.9.1`.

**Comment by CoenraadS** [comment]
Thanks for the report. Unfortunately I am on vacation but hope to fix this
when I return.

**Comment by CoenraadS** [comment]
As a temporary workaround you can download an older version from the
Releases section on GitHub and install the old version manually

**Comment by CoenraadS** [comment]
Most likely I have imported a file with wrong capitalization, because I
only test on Windows which has a case insensitive filesystem

**Comment by CoenraadS** [comment]
I just setup Ubuntu, however it seems to work ok for me. There was only a capitalisation issue in the test which shouldn't affect the extension. Afraid I can't reproduce this.

![image](https://cloud.githubusercontent.com/assets/5593825/25288606/6325a60a-26c6-11e7-8ed9-51e96e35787f.png)

Do you have any custom settings?

**Comment by tiangolo** [comment]
I just saw that I can turned on "Developer Tools", and there's an error that doesn't appear in the status console.

Here's everything that I get in my console:

```
Overwriting extension <<.conf>> to now point to mime <<text/x-NGINX>>
Conflict detected, command `workbench.action.openRecent` cannot be triggered due to npm-script.showOutput
Conflict detected, command `workbench.action.openRecent` cannot be triggered due to npm-script.run
Conflict detected, command `workbench.action.openRecent` cannot be triggered due to npm-script.rerun-last-script
Conflict detected, command `workbench.action.openRecent` cannot be triggered due to npm-script.terminate-script
Conflict detected, command `workbench.action.openRecent` cannot be triggered due to npm-script.test
[Extension Host] Activating extension `CoenraadS.bracket-pair-colorizer` failed: Cannot find module './multipleIndexes'.
[Extension Host] Activating extension `CoenraadS.bracket-pair-colorizer` failed:  Cannot find module './multipleIndexes'
[Extension Host] Here is the error stack:  Error: Cannot find module './multipleIndexes'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/.vscode/extensions/CoenraadS.bracket-pair-colorizer-0.10.1/out/src/lineState.js:4:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
Activating extension `CoenraadS.bracket-pair-colorizer` failed: Cannot find module './multipleIndexes'.
```

Also, I restarted the full system (just in case) and removed completely and re-installed the extension.

Does that log give you any ideas?

**Comment by CoenraadS** [comment]
Someone else has an identical issue: https://github.com/CoenraadS/BracketPair/issues/20

But atm I have no idea why module multipleIndexes won't load

**Comment by CoenraadS** [comment]
For some reason during the packaging step, the file `multipleIndexes` became `MultipleIndexes`

I just recompiled and it seems ok now, please try the latest version..

**Comment by tiangolo** [comment]
Awesome! Thanks for the great work @CoenraadS . It is working now! :tada:

**Comment by dhgiang** [comment]
Works for .ts file, but not in html files

**Comment by GunnerJnr** [comment]
I second @dhgiang these '{{ }}' don't work in HTML files in Angular, but you can add this:

`[
			"</",
			">"
		],
		[
			"<",
			"/>"
		],
		"<>",`

So that the html tags colourise too
