### ISSUE TITLE
Is there a way to disable coloring in comments?

### ISSUE THREAD

**Issue by GollyJer** [CoenraadS/BracketPair#24]
Here is an example of what I'm seeing in my `.js` file.
![2017-05-24_12h10_09](https://cloud.githubusercontent.com/assets/689204/26413669/b3c436da-407a-11e7-8dd0-872ee546f801.png)
Is there a setting to disable comment coloring?

**Comment by CoenraadS** [comment]
There is one, however it should be enabled by default, so I'm not sure why its not working for you.

`"bracketPairColorizer.contextualParsing": true`

If you manually set the file to javascript (ctrl + shift + p, choose language, javascript) does it help?

**Comment by GollyJer** [comment]
Hi @CoenraadS. Thanks for the reply!

That is the issue.  I'm using `javascriptreact` as the file type. When I switch to plain `javascript` I no longer get highlighting.
![screenshot_01](https://cloud.githubusercontent.com/assets/689204/26417300/cae6ddde-4086-11e7-981e-fc05539deb50.png)


Here is the [Sublime Babel extension info](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode).  It provides much better syntax highlighting for React development. 

**To get your and their extension working together do I need to reach out to them?**

**Comment by CoenraadS** [comment]
Currently I have to create manual parse rules per language to detect comments/strings. If there is no differences between javascriptreact and javascript commenting styles it should be a simple fix on my end.

**Comment by CoenraadS** [comment]
Please try 0.10.4

**Comment by GollyJer** [comment]
Boom!!
![screenshot_02](https://cloud.githubusercontent.com/assets/689204/26418966/2e8cd686-408c-11e7-8c99-8a7c520a38f3.png)
Thanks!!!

**Comment by chandramuralis** [comment]
I still see the coloring in the comments in js file

![image](https://user-images.githubusercontent.com/760056/39006107-16dea36e-43d0-11e8-8f12-4003d46f192f.png)

**Comment by CoenraadS** [comment]
Could you paste the whole block as text so I can copy it to test

**Comment by chandramuralis** [comment]
// gulp.task('web', function () {
//     gulp.src(HtmlFiles)
//         .pipe(injectVersion())
//         .pipe(gulp.dest(DIST));

**Comment by CoenraadS** [comment]
I think I need the above scope too, not sure what is breaking it atm

![image](https://user-images.githubusercontent.com/5593825/39006585-cba05f4e-4403-11e8-83de-358004ba644e.png)

**Comment by chandramuralis** [comment]
This is another example....
// gulp.task('site', function () {
//     gulp.src(siteHTMLFiles)
//         .pipe(injectVersion())
//         .pipe(gulp.dest(DIST_DIR));
// });

May be is it caused by another plugin?

**Comment by CoenraadS** [comment]
Maybe, I've had conflicts before with plugins that also use PrismJs because it conflicts with Node globally.

Try posting the output of `code --list-extensions` and I'll take a look

**Comment by chandramuralis** [comment]
$ code --list-extensions  

Angular.ng-template
CoenraadS.bracket-pair-colorizer
EditorConfig.EditorConfig
GregorBiswanger.json2ts
HookyQR.beautify
PKief.material-icon-theme
SirTori.indenticator
adamwalzer.scss-lint
alefragnani.Bookmarks
alefragnani.project-manager
amatiasq.sort-imports
christian-kohler.path-intellisense
donjayamanne.githistory
eamodio.gitlens
eg2.tslint
eriklynd.json-tools
felipecaputo.git-project-manager
jakethashi.vscode-angular2-emmet
johnpapa.angular-essentials
johnpapa.Angular2
johnpapa.winteriscoming
liximomo.sftp
lonefy.vscode-JS-CSS-HTML-formatter
michelemelluso.code-beautifier
mrmlnc.vscode-apache
msjsdiag.debugger-for-chrome
natewallace.angular2-inline
oderwat.indent-rainbow
patrys.vscode-code-outline
redhat.java
sodatea.velocity
steoates.autoimport
vscjava.vscode-java-debug
wayou.vscode-todo-highlight
wcwhitehead.bootstrap-3-snippets
ziyasal.vscode-open-in-github
