### ISSUE TITLE
Add contextual parsing for Dart?

### ISSUE THREAD

**Issue by Qwerp-Derp** [CoenraadS/BracketPair#26]
Dart's syntax relevant to contextual parsing (i.e. comments and strings) is basically the same as other C-like languages.

Comments:

    // This is a comment
    /*
      This is
      a multi-line
      comment. */

Strings:

    "This is a string"
    'This is also a string'

**Comment by CoenraadS** [comment]
It has been added to 0.10.7. Please let me know if there are any issues.
