### ISSUE TITLE
BracketPair Settings: Cannot read property 'ClosedClosed' of undefined

### ISSUE THREAD

**Issue by SanderElias** [CoenraadS/BracketPair#27]
I get the following error that pops up in my code-insiders:
```
BracketPair Settings: Cannot read property 'ClosedClosed' of undefined
```
and the colorization does not work. What can I do?

**Comment by CoenraadS** [comment]
Its because it relies on a new API in VSCode, so all you have to do is update.

**Comment by SanderElias** [comment]
That did the trick! :-D
