### ISSUE TITLE
[feature req: Color Highlight of Active bracket]

### ISSUE THREAD

**Issue by martinandersen3d** [CoenraadS/BracketPair#30]
When you are inside of a bracket ( some text here), while you write inside of it, it will highlight those bracket.

**Comment by warpdesign** [comment]
I second to that: I really wish only the current active bracket would be highlighted, and not any open/close brackets.

```js
function foo() {
    if () {
       // if cursor is here, only the if opening/closing brackets are hilighted
    }
}

**Comment by CoenraadS** [comment]
`"bracketPairColorizer.highlightActiveScope": true`
