### ISSUE TITLE
Cursor position broken in VSCode Insiders

### ISSUE THREAD

**Issue by kumarharsh** [CoenraadS/BracketPair#34]
Hi, I've been using this plugin for quite some time, and it's really great! But in the latest vscode insiders builds, (1.14), this plugin causes my cursor to skip when I press return. When I disable this plugin, everything works fine.

Example: 

Make a css file. type this:

```
.classA,.classB
```
Now, bring your cursor (`|`) after the `comma`:

```
.classA,|.classB
```
and press <kbd>Enter</kbd>

The result should be:

```
.classA,
|.classB
```

But the result is:

```
.classA,
.classB|
```

This happens in all files (HTML, JSX, CSS, JS, etc) and causes indentation to break, sometimes cursor to go one character back in JS code, indentation shortcuts to misbehave, etc.

**Comment by CoenraadS** [comment]
Strange bug since I don't manipulate the cursor position at all. I couldn't reproduce in 1.14 insider unfortunately so hard for me to track down the cause.

**Comment by kumarharsh** [comment]
Hi @CoenraadS - today I'm getting this bug even with your plugin disabled. I think it's due to some other plugin. I'll continue investigating, but will be closing this issue.
