### ISSUE TITLE
brackets color will be different when there is a regexp between them

### ISSUE THREAD

**Issue by hsqs** [CoenraadS/BracketPair#36]

**Comment by Moeriki** [comment]
Problem is with any escaped character.

![image](https://user-images.githubusercontent.com/38758/28668235-3227ed60-72cf-11e7-9a84-5c13dad7576e.png)

**Comment by CoenraadS** [comment]
Yea my custom parser is pretty basic and will fail often. I need to find the time to rip it out and replace it with a better solution such as http://prismjs.com/

**Comment by luchillo17** [comment]
Same here, though my case was a bit bigger:
![image](https://user-images.githubusercontent.com/9698639/32148106-d76a7f42-bcbf-11e7-8d1f-4fcd9e1db2e7.png)

**Comment by CoenraadS** [comment]
Should be fixed in latest
