### ISSUE TITLE
Brackets shouldn't be colored in markdown

### ISSUE THREAD

**Issue by erichiller** [CoenraadS/BracketPair#43]
Brackets either shouldn't be colored in markdown, or should have the option. Currently, and time I use parenthesis in markdown, I have a bunch of erroneous colorization. A simple option to disable for certain file types would suffice.

**Comment by CoenraadS** [comment]
I like this idea but won't be working on this until I'm back from vacation
in September

**Comment by CoenraadS** [comment]
Finally fixed this I think..

**Comment by ketozhang** [comment]
@CoenraadS 

Did you completely remove this feature from Markdown? I type LaTeX in Markdown so the bracketPair is useful (adding custom settings to color `$\LaTeX$` pairs. I don't see any settings to enable/disable Markdown bracket pair coloring

**Comment by CoenraadS** [comment]
It changed from basic text parsing being applied on all documents, to
syntax parsing being used for supported languages. I'm thinking about a way
to reintroduce the old behavior for non-supported languages

**Comment by ketozhang** [comment]
Is there a list of supported languages. The documentation claims all of [Prism](http://prismjs.com/#languages-list) is but Prism does support Markdown

**Comment by CoenraadS** [comment]
Sometimes the prism languages and vscode language is doesn't match up. I
probably just need to manually map the language IDs and it will work for
basic markdown syntax. I'll try to push a fix later today

**Comment by CoenraadS** [comment]
I added checking brackings in markdown urls in v1.0.16

Let me know if you expect parsing on other elements

**Comment by ketozhang** [comment]
I want to parse dollar signs for LaTeX in Markdown. Not everyone uses Markdown LaTeX so it's best to have it customize-able in settings.

Maybe a setting that looks like:

```json
"bracketPairColorizer.consecutivePairColors": [
    "default",
        [
            "()",
            "[]",
            "{}",
            [
                "Gold",
                "Orchid",
                "LightSkyBlue"
            ],
            "Red"
        ],
    "markdown",
        [
            "$$",
            [
                "Orchid",
            ],
            "Red"
        ],
]
```

**Comment by CoenraadS** [comment]
I agree I need to support different pairs per language

**Comment by Anmol-Singh-Jaggi** [comment]
+1
First of all, thanks for making such a useful extension. 
I am using a custom version of markdown in which brackets are meaningful (long story). It would be incredibly useful if there was a way to re-enable it in markdown.
