### ISSUE TITLE
Support for Ruby/Crystal regex?

### ISSUE THREAD

**Issue by Qwerp-Derp** [CoenraadS/BracketPair#45]
Ruby regexes' syntax are like so:

```ruby
regex = /\w+/
# Above is a regex, delimited
# with /{regex}/.
```

This shouldn't match something like `1 / (2 + 3) / 4`, `(2 + 3)` is not a regex. A regex is only identified as such when it is:

- the first thing in a line
- following a `=` sign
- inside `[]`, `()`, or `{}`

**Comment by CoenraadS** [comment]
Should be fixed in latest
