### ISSUE TITLE
Arrow functions in JS/TypeScript seem to confuse the outer delimiter colorings

### ISSUE THREAD

**Issue by mindjuice** [CoenraadS/BracketPair#46]
The following is a simplified snippet of JS code that causes the bug.  The same bug occurs if you add type annotations.

This code colorizes correctly (even though it doesn't make sense for the `_.each()` function):
```js
_.each(
  a, {}
)
```

This code doesn't colorize correctly:
```js
_.each( /* <--- This paren is a different color */
  a, x => {} /* Add arrow function here */
) /* <--- than this paren */
```

NOTE: Running version `0.10.8`

**Comment by CoenraadS** [comment]
Should be fixed in latest release
