### ISSUE TITLE
Slow when switching from a large file to a small one

### ISSUE THREAD

**Issue by dahbored** [CoenraadS/BracketPair#48]
Every time I switch from a large file (20,000+ lines) to another file, VS Code freezes for 3-5 seconds (even longer if I'm debugging).
I tried disabling all the extensions and enabling them one by one, and it seems like BracketPair is causing the issue. 

About Visual Studio Code:

- Version 1.16.0
- Shell 1.7.3
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

**Comment by CoenraadS** [comment]
I now only color the first 5000 lines
