### ISSUE TITLE
Dont work with *.rs files properly

### ISSUE THREAD

**Issue by Doaxan** [CoenraadS/BracketPair#49]
Dont work with *.rs files properly with rust language mode
0.10.9

Version 1.16.1
Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
Date 2017-09-14T16:26:20.018Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Doaxan** [comment]
![image](https://user-images.githubusercontent.com/9551541/30523594-a09fd992-9bec-11e7-80d5-fd04a6f6ed67.png)

**Comment by Doaxan** [comment]
If i use "Plain text" mode, extension works good.

**Comment by CoenraadS** [comment]
wow this was completely broken, I don't use rust so never realized.

Hopefully it works a bit better now in v0.10.12. Its built targeting the insiders version of vscode so if you are on stable channel you will have to wait until v18 ships.

**Comment by AradiPatrik** [comment]
Still having this issue

**Comment by CoenraadS** [comment]
I'll track this in your other issue: https://github.com/CoenraadS/BracketPair/issues/85
