### ISSUE TITLE
Color confusion in natural language

### ISSUE THREAD

**Issue by LeThiHyVong** [CoenraadS/BracketPair#58]
Now your only support to input colors in natural language. 
I'm not a native English speaker. Even in my native language, there are a lot confusion in colors. Some color, such as "DeepPurple", aren't recognized. But I can't found the list anywhere in your description. 
So could you help to do at least one of below:
1. Provide a list of supported color
2. Support color codes

Thanks.

**Comment by CoenraadS** [comment]
https://www.w3schools.com/cssref/css_colors.asp

You should also be able to use the hex color format.
