### ISSUE TITLE
Consecutive bracket coloring

### ISSUE THREAD

**Issue by con-ssc** [CoenraadS/BracketPair#6]
Currently, you only seem to change color if use of the same kind of brackets. Would it be possible to change color on every configured opening bracket also if they are of a different kind?

**Comment by CoenraadS** [comment]
Yes I also wanted this feature, I hope to add it soon.

**Comment by CoenraadS** [comment]
It has been added in v0.1.0

**Comment by Arithmeticae** [comment]
Can this be made an option and not a forced behavior? I prefer to have brackets at the same level to have the same color (the way Rainbow Brackets) behaves.

**Comment by CoenraadS** [comment]
I hope to add it as an option soon

**Comment by CoenraadS** [comment]
It is now behind an option forceUniqueOpeningColor in v0.2.0

**Comment by CoenraadS** [comment]
@Arithmeticae 

If you use Independant mode with the same colors in all of them (like default settings), you get same colors for same scopes

**Comment by CoenraadS** [comment]
@Arithmeticae 

If you use Independent color mode you should get brackets at same scope with same color.

There was a bug in the previous version that would increment colors outside of scope, that is now behind a setting.

**Comment by Arithmeticae** [comment]
Gave the new build a go, works beautifully, thank you.
