### ISSUE TITLE
[Future Development] Adding coloured line?

### ISSUE THREAD

**Issue by gsivaprabu** [CoenraadS/BracketPair#61]
Hi,

Possible to add this type of future ? Red dotted lines where to close like

![highlighter](https://user-images.githubusercontent.com/2444608/33978571-688861a4-e0c6-11e7-8273-9edc2a6b9f7a.png)
![highlighter2](https://user-images.githubusercontent.com/2444608/33978572-68b5862a-e0c6-11e7-8d6a-6b410f994726.png)

**Comment by CoenraadS** [comment]
Happy to hear some feedback. You can customize this in v1.0.5

```
"editor.matchBrackets": false,
"bracketPairColorizer.highlightActiveScope": true,
"bracketPairColorizer.activeScopeBorderStyle": "1px dotted red; opacity: 0.65",
```
