### ISSUE TITLE
doesn't work after comment. 

### ISSUE THREAD

**Issue by ntnbst** [CoenraadS/BracketPair#63]
here is a problem working with html in angular, after commenting something it stops working from that point. 
![222](https://user-images.githubusercontent.com/25779687/34456994-7bf98fcc-edca-11e7-9010-d43e3aa1e34e.gif)

**Comment by CoenraadS** [comment]
Can you please test this with the latest release v1.0.1?

If it still occurs could you provide some text I can copy/paste to test myself.
