### ISSUE TITLE
Single quote breaks highlighting for jsx file

### ISSUE THREAD

**Issue by Graham42** [CoenraadS/BracketPair#65]
I have a jsx file where the bracket highlighting works until part way through the file. Experimenting I found it's caused by the apostrophe / single quote (`'`)

Steps to reproduce:
1. Create a new `.jsx` file
2. Paste this sample code into it
    ```
    function xyz() {
      return () => "this works";
    }
    
    const Breaking = () => <p>the single quote breaks this, it's unfortunate </p>;
    
    class Foo extends React.Component {
      render() {
        //...
      }
    }
    ```
3. The highlighting for class Foo shouldn't work.
4. Remove the apostrophe from the word `it's` in the `Breaking` component. 
5. The highlighting should now work.

**Comment by CoenraadS** [comment]
Should be fixed in v1.0.1
