### ISSUE TITLE
Facing issue with RegExp

### ISSUE THREAD

**Issue by sheikalthaf** [CoenraadS/BracketPair#67]
Hi,

I'm facing issue when some regexp is used like this ```[!@#$%^&*(){}[\]<>?/|\-:;"'.,_+=`~]```

**Comment by Tadaboody** [comment]
[Same here](http://prntscr.com/iipprz). Seems like brackets inside of RegExp confuse it.

**Comment by CoenraadS** [comment]
Please test with the latest release >v1.0.1 if this still occurs

**Comment by Tadaboody** [comment]
[excellent](http://prntscr.com/ij6mjr) 🥇
