### ISSUE TITLE
Not Colorizing Project Previous To Installation

### ISSUE THREAD

**Issue by markwartman1** [CoenraadS/BracketPair#68]
Hello,

     User story: I built some applications.  Later, I installed the Bracket Pair Colorizer, Awesome!.  The bracket pair colorizing did not take place in the project that I was currently working on until I restarted VS_Code.  After restarting vsCode, the colorizing initialized, Awesome.
  
     However, previously built projects are not implementing the colorizer.  The colorizer is not working with previously built projects.  Is this normal?  I tried disabling and then relabeling while working on those project to trigger an initialization, and I also tried editing a bracket or pair of parenthesis to trigger the Bracket Pair Colorizer to work but unfortunately it is not working.  Please advise.

Thank you.

**Comment by markwartman1** [comment]
Particularly pertaining to HTML files.

**Comment by markwartman1** [comment]
The Bracket Pair Colorizer does not colorize past HTML comments, but I think I recall seeing someone else suggested this.

Thanks.

**Comment by CoenraadS** [comment]
Does it still occur with the latest version? Some file types such as Vue arn't supported
