### ISSUE TITLE
Not working for HTML files

### ISSUE THREAD

**Issue by GargantulaKon** [CoenraadS/BracketPair#77]
This is not working for HTML files. I am working on an Angular 5 project and it works for TypeScript files, but I don't see my brackets being colorized in Visual Studio Code v1.20.1.

**Comment by CoenraadS** [comment]
What language does vscode report for these files? It shows in the bottom right corner:

![image](https://user-images.githubusercontent.com/5593825/36646103-52c1d972-1a73-11e8-87dc-31b45496ade7.png)

**Comment by CoenraadS** [comment]
nvm I found the bug, thanks for reporting 👍

**Comment by GargantulaKon** [comment]
You're welcome. Did it break in a future version of Visual Studio Code? I
thought it was working in previous versions.

**Comment by CoenraadS** [comment]
I offloaded parsing to an external library so I don't have to maintain it myself. However it means I have less control over certain things.

You can download an older version from https://github.com/CoenraadS/BracketPair/releases in the meantime.

**Comment by GargantulaKon** [comment]
Thanks v0.10.8 works for me for HTML files.

**Comment by CoenraadS** [comment]
Hopefully its working now, but it requires some configuration changes.

Here is an example config:

```
    "bracketPairColorizer.consecutivePairColors": [
        [
            "</",
            ">"
        ],
        [
            "<",
            "/>"
        ],
        "<>",
        [
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        "Red"
```

**Comment by wellfrog16** [comment]
it not working for vue
![112](https://user-images.githubusercontent.com/22096815/36686730-52265282-1b62-11e8-9c29-4296f48ce54f.png)

**Comment by CoenraadS** [comment]
Yes Vue is not supported by PrismJS unfortunately. I also would like to support it

**Comment by thedamon** [comment]
that HTML string doesn't work for me in settings.. i'm not really sure what the format of the new pairs is supposed to be...

**Comment by CoenraadS** [comment]
Could you share the file you are trying to parse, as well as the language associated with it?

**Comment by thedamon** [comment]
I mean specifically with the example `"bracketPairColorizer.consecutivePairColors"` config you posted and is now in the readme. I get syntax errors in the JSON, including when I add the extra `]` (?) i get `consecutivePairColors[ 0] is not a string`. But I'm really unsure how that formatting is supposed to work.

**Comment by CoenraadS** [comment]
You may need to update the extension

**Comment by GargantulaKon** [comment]
I tried the new version and the config settings you put, but I still don't see the brackets colorized when using [(ngModel)] in my HTML file. On the old version, it works. I tried adding the rest of the brackets to the consecutivePairColors object with no luck.

**Comment by CoenraadS** [comment]
Would you find pasting your full settings file?

**Comment by CoenraadS** [comment]
Yes the Angular parsing may work differently now. I'm not sure PrismJs returns the []'s as punctuation types. I'll take a look at this.

**Comment by CoenraadS** [comment]
![image](https://user-images.githubusercontent.com/5593825/36746582-f8434cfc-1bf2-11e8-80bc-d0288d041ddb.png)

There is some basic attribute support now added. I'm going to close this issue and track further development in https://github.com/CoenraadS/BracketPair/issues/79

**Comment by CoenraadS** [comment]
Also as a FYI, in v1.0.12 you can now simply use "<>" to partially match "<" "</", "/>" ">"

**Comment by joshkellough** [comment]
Hi. Colorization isn't working on HTML for me either. I went to #79 but I'm not using Angular. Would you like me to open another issue or elaborate more here? Thank you.

**Comment by CoenraadS** [comment]
Yes please open another issue. Post your settings, extension version and some sample code + the language you are using.

**Comment by joshkellough** [comment]
I will, thank you. Is the json file supposed to be colorized?

**Comment by CoenraadS** [comment]
@joshkellough yes

**Comment by joshkellough** [comment]
Thanks. I'll have more for you tomorrow.
