### ISSUE TITLE
Brackets in JSON strings are colorized if a single quote is used

### ISSUE THREAD

**Issue by nikoladev** [CoenraadS/BracketPair#78]
This extension starts coloring brackets in strings in JSON files if a single quote is used:

![image](https://user-images.githubusercontent.com/15011519/36681173-29bde9ee-1b18-11e8-92dc-b42b3f08e548.png)

And then the bracket highlighting for some reason doesn't register the opening parentheses which makes the curly braces at the end not registering the opening curly brace. Maybe that's a hint for the bug?

**Comment by CoenraadS** [comment]
I filed an issue at PrismJS: https://github.com/PrismJS/prism/issues/1308

**Comment by CoenraadS** [comment]
Should be fixed in 1.0.10

**Comment by nikoladev** [comment]
Can confirm it's fixed. Thanks!
