### ISSUE TITLE
PowerShell syntax for array is not parsed correctly

### ISSUE THREAD

**Issue by Jawz84** [CoenraadS/BracketPair#80]
Let me start by saying: THANK YOU for this great tool!

## Versions
* Visual Studio Code: 
  Version 1.20.1
  Commit f88bbf9137d24d36d968ea6b2911786bfe103002
  Date 2018-02-13T15:34:36.336Z
  Shell 1.7.9
  Renderer 58.0.3029.110
  Node 7.9.0
  Architecture x64
* Plugin versions: 
  BracketPair 1.0.12
  PowerShell 1.16.0

## How to reproduce:
My settings are all standard, no customizations. 

Start new VSCode tab, paste this, set filetype to PowerShell (Ctrl+K M, select PowerShell <enter>)
```powershell
function foo {
    [string[]]$thing
}
```
### Expected result:
- The { }-bracket pair is colored yellow,
- The [ ]-bracket pair around 'string[]' is colored purple,
- The [ ]-bracket pair after 'string' is colored cyan.

### Actual result: 
![image](https://user-images.githubusercontent.com/26464885/36848651-2bb92f0a-1d62-11e8-975f-62af06889bdf.png)

**Comment by CoenraadS** [comment]
Nice one, fixed on 1.0.13

**Comment by Jawz84** [comment]
Thanks for the fast fix. I've already used it! Great!

Op 1 mrt. 2018 5:36 p.m. schreef CoenraadS <notifications@github.com>:

Nice one, fixed on 1.0.13
