### ISSUE TITLE
Javascript comments containing /**/ not parsed correctly

### ISSUE THREAD

**Issue by wellfrog16** [CoenraadS/BracketPair#83]
wrong
![1122](https://user-images.githubusercontent.com/22096815/37073288-e850a574-2200-11e8-956e-2446ce526ea2.png)

wrong
![2](https://user-images.githubusercontent.com/22096815/37073367-76ed179a-2201-11e8-923e-d73e849358f0.png)

right
![3](https://user-images.githubusercontent.com/22096815/37073370-7b03f98e-2201-11e8-9353-6498f550a1d2.png)

**Comment by CoenraadS** [comment]
Thanks for the report, the bug is that it sees `/**/` as the end of the comment. I filed a bug with prismjs: https://github.com/PrismJS/prism/issues/1337

**Comment by CoenraadS** [comment]
Fixed in 1.0.19

**Comment by CoenraadS** [comment]
Unfortunately the fix for this broke some other stuff, so I reverted the fix

**Comment by CoenraadS** [comment]
Should be fixed in v1.0.28
