### ISSUE TITLE
It doesn't work in vscode since update to 1.0.16 @CoenraadS 

### ISSUE THREAD

**Issue by jcbwcj** [CoenraadS/BracketPair#84]
![1nc jv5ux3 z ooag 85r5](https://user-images.githubusercontent.com/29140891/37092402-ba062450-2246-11e8-8730-660ed3b3bc48.png)

**Comment by CoenraadS** [comment]
Thanks for the report, I have a fix ready, should be released later today
after I test it a bit more

**Comment by CoenraadS** [comment]
please try v1.0.17

**Comment by CoenraadS** [comment]
I will track vue in this issue: https://github.com/CoenraadS/BracketPair/issues/84#issuecomment-371346864
