### ISSUE TITLE
Rust generic lifetime parameters break parantheses matching.

### ISSUE THREAD

**Issue by AradiPatrik** [CoenraadS/BracketPair#85]
![image](https://user-images.githubusercontent.com/16306605/37113345-74418852-2245-11e8-9915-3a9e7d4af73f.png)
Seems like BracketPair treates lifetime parameters in rust, like regular strings, so it breaks highlighting.

**Comment by CoenraadS** [comment]
I fixed this months ago and now it's back to haunt me :( 

https://github.com/PrismJS/prism/issues/1339

**Comment by CoenraadS** [comment]
Fixed in 1.0.19
