### ISSUE TITLE
This quit working with Vue last week when I came into work.

### ISSUE THREAD

**Issue by JynxLee** [CoenraadS/BracketPair#86]
I've been using this as part of the VScode extension pack "Vue VSCode Extension Pack" by sarah.drasner.
I've reinstalled VScode.  I've uninstalled the pack and install bracket pair all by itself.  No joy.  What I have noticed though is that if it is a JavaScript .js file only in my store that the brackets are colored.  If its in any of my .vue files mixed with JavaScript and html then no brackets are colored.  I believe it was the morning of 3/1/18 that I came into the office to find it no longer working.

**Comment by CoenraadS** [comment]
Duplicate: https://github.com/CoenraadS/BracketPair/issues/15

Try the new release (v1.0.18), happy to hear some feedback
