### ISSUE TITLE
JSONC: key containing /* breaks further brackets highlight

### ISSUE THREAD

**Issue by myfonj** [CoenraadS/BracketPair#89]
```js
{ "/*": [{}] } 
```
![image](https://user-images.githubusercontent.com/1761395/37196589-b1a3a5e4-2377-11e8-8352-9a1d60cd83c4.png)

Supposedly regression, worked well few versions back IIRC.
Possibly related  #88 (?)

**Comment by CoenraadS** [comment]
Thanks, I think I will roll back the previous release but might take until
Saturday

**Comment by myfonj** [comment]
NB there was VSC version bump to 1.21.0 in the meantime; seeing relation to Prism core in the other issue suggests it might be connected as well.

**Comment by CoenraadS** [comment]
Ok the old behaviour is back in v1.0.20

**Comment by myfonj** [comment]
Great to see it fixed indeed!

May I ask, **is it really necessary to operate on own/extra parser**? Isn't it possible to co-operate with existing language servers (or what is it called) VSC already uses for its own highlighters?

(Pardon most probably silly question and hijacking irrelevant channel, I was shy to create extra issue just to ask.)

**Comment by myfonj** [comment]
Ah, that's a shame really. And does not make much sense either. Now I'm afraid to know how many redundant parsers runs in extensions I have installed just to be able to "select strings", "see brackets", "see indentation" and so on.  And how much more extra power it consumes :|

Thanks for answer though!

Reading though that issue and Microsoft/vscode#580 Microsoft/vscode#585 does not leave much hope…
