### ISSUE TITLE
Rust char, and byte literals break bracket highlight

### ISSUE THREAD

**Issue by AradiPatrik** [CoenraadS/BracketPair#90]
Probably related to the previous fix. The static lifetime parameters work well, but byte literals and character literals break bracket highlight.
![issue](https://user-images.githubusercontent.com/16306605/37247127-b6838d50-24b6-11e8-8df5-0938f0fde83f.png)
The bad highlighting can be seen on line 6 and 17.

**Comment by CoenraadS** [comment]
Should be fixed in v1.0.21
