### ISSUE TITLE
Problem with nested strings and hash

### ISSUE THREAD

**Issue by DarthZetha** [CoenraadS/BracketPair#92]
I'm working with python and I have to generate xml files where the lines will contain both " and #.
It seems that if I have both an ' and an " before a #, the bracket coloring stops working.

This is a very simple replication of the problem:
![image](https://user-images.githubusercontent.com/21339416/37297623-6e38d2b2-261e-11e8-9140-e6be03ba0da9.png)

**Comment by CoenraadS** [comment]
Tracking here: https://github.com/PrismJS/prism/issues/1355

**Comment by CoenraadS** [comment]
Should be fixed in  v1.0.28
