### ISSUE TITLE
XQuery support

### ISSUE THREAD

**Issue by KWeaver87** [CoenraadS/BracketPair#93]
I'm working with the XQuery language at work. BracketPair prior to the PrismJS update supported XQuery okay, but since that update it doesn't handle the language at all. For now, I've reverted to BracketPair 0.10.8, but it's a bit obnoxious when VSCode randomly decides to remove BracketPair inbetween sessions.

Running VS Code 1.21.0 with XQuery support from [XML Tools](https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml) 1.9.2

**Comment by CoenraadS** [comment]
Thanks for your report. I took a look at XQuery, and while it isn't supported by PrismJs, it seems to have a similar structure as SQL which is.

Could you test if manually changing the language ID to SQL `(ctrl-k, m)` makes it colorize properly? If it does I will map it also in the code.

**Comment by KWeaver87** [comment]
I pulled example 9-18 from the [Xquery book](http://www.datypic.com/books/xquery/chapter09.html) and took some screenshots.
The best sample code I can recommend is the [FunctX Function Library](http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq), which contains most combinations of (), {}, [], and comments that I can find.
Also not visible in my screenshots, BracketPair 0.10.8 would highlight the comment parenthesis. Which is not a big deal at all.

Running BracketPair 0.10.8:
![Imgur](https://i.imgur.com/YrLKq2E.png)

Running BracketPair 1.0.20, language set to XQuery:
![Imgur](https://i.imgur.com/G1K91MI.png)

Running BracketPair 1.0.20, language set to SQL:
![Imgur](https://i.imgur.com/k8QXnCP.png)

**Comment by CoenraadS** [comment]
That would be great!

**Comment by KWeaver87** [comment]
Created new issue here: PrismJS/prism#1405

**Comment by CoenraadS** [comment]
New PrismJS is included in v1.59. Let me know if it doesn't work

**Comment by KWeaver87** [comment]
Everything seems to work good. Thanks for the update!
![image](https://user-images.githubusercontent.com/28742312/42344964-eef6bc0a-806b-11e8-848e-80635ebb1ec4.png)
